### PR TITLE
Fixing Chart Colors and Severity Bars.

### LINKED ISSUE #64: Severity Bars not showing on chart

### PR DESCRIPTION
**Pull request by llvasconcellos**
This fixes #64
Simple fix to a difficult to find bug.

### CODE REVIEW

File: app/src/main/java/org/projectbuendia/client/ui/chart/ObsFormat.java [hunk 1]
```diff
@@ -456,7 +456,7 @@ private boolean matches(@Nullable Object obj, String operator, String operandStr
                 case "":
                 case "=":
                 case "==":
-                    return Objects.equal(value, operand);
+                    return Objects.equal(value.uuid, operand.uuid);
```
Comment (zestyping) [inline app/src/main/java/org/projectbuendia/client/ui/chart/ObsFormat.java:459]: This doesn't look right to me.  If we let ObsValue.equals() do the comparison, it will check all its fields.  With this change, all numbers, strings, or dates will compare equal even though they shouldn't.

What was the root cause of the incorrect behaviour you were seeing, and how did this change fix it?

File: app/src/main/java/org/projectbuendia/client/ui/chart/PebbleExtension.java [hunk 2]
```diff
@@ -192,6 +192,8 @@ public Object apply(Object input, Map<String, Object> args) {
                 for (Object item : (Collection) input) {
                     values.add(item instanceof ObsValue ? (ObsValue) item : null);
                 }
+            } else if (input instanceof ObsValue) {
```
Comment (zestyping) [inline app/src/main/java/org/projectbuendia/client/ui/chart/PebbleExtension.java:195]: I'm curious, how did this change help fix the problem?

I ask because it was the original intention for this filter to not handle an individual value; format_value is supposed to take an individual value and format_values is supposed to take a list or array of values.

File: app/src/main/java/org/projectbuendia/client/ui/chart/ObsFormat.java (hunk 1 above)
Comment (llvasconcellos) [inline app/src/main/java/org/projectbuendia/client/ui/chart/ObsFormat.java:459]: Yes,  probably this not a right fix for the problem.  The thing is that operand.name was  null.

File: app/src/main/java/org/projectbuendia/client/ui/chart/PebbleExtension.java (hunk 2 above)
Comment (llvasconcellos) [inline app/src/main/java/org/projectbuendia/client/ui/chart/PebbleExtension.java:195]: Sometimes input  is a instance of  ObsValue not an array  or collection.

File: app/src/main/java/org/projectbuendia/client/ui/chart/ObsFormat.java (hunk 1 above)
Comment (zestyping) [inline app/src/main/java/org/projectbuendia/client/ui/chart/ObsFormat.java:459]: Oops, it looks like this line 459 change got committed.  Would you mind reverting it?

File: app/src/main/java/org/projectbuendia/client/ui/chart/PebbleExtension.java (hunk 2 above)
Comment (zestyping) [inline app/src/main/java/org/projectbuendia/client/ui/chart/PebbleExtension.java:195]: When is the input a single instance of ObsValue?  Can that call site use format_value instead of format_values?
